eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

server:
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/base31?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:db2://127.0.0.1:50000/basedb
#    driver-class-name: com.ibm.db2.jcc.DB2Driver
#    username: db2inst1
#    password: db2inst1

#    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    username: basedb
#    password: basedb
    max-idle: 10
    min-idle: 5
    test-on-borrow: false
    time-between-eviction-runs-millis: 18800
    test-while-idle: true
    validation-query: SELECT 1
    hikari:
      minimum-idle: 0
  redis:
    host: 127.0.0.1
    port: 6379
    #password: 123456

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: base
    listener:
      simple:
        retry:
          enabled: true #启用重试
          max-attempts: 5 #重试最大次数
          max-interval: 10s #重试最大间隔时间
          initial-interval: 5s #重试初始间隔时间
          multiplier: 2 #间隔时间乘子,间隔时间*乘子=下一次的间隔时间,最大不能超过设置的最大间隔时间
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 127.0.0.1:9300
  autoconfigure:
    #关闭rabbitmq
    exclude:
      org.springframework.cloud.bus.BusAutoConfiguration,org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

redis:
  cache:
    expiration: 3601

ribbon:
  eager-load:
    enabled: true
    clients: base-cloud-auth,base-cloud-user-service
  Httpclient:
    enabled: true
  OkHttp:
    enabled: false
  ReadTimeout: 600000
  ConnectTimeout: 60000

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: false
  httpclient:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 6000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 1800000
components:
  messageQueue: false
